### PR TITLE
Fix : Clicks_count published on RMQ

### PR DESCRIPTION
**Pull request by Nazi-pikachu**
### Description
This PR enables the RMQ for increasing click-counts as per the HLD and fixes few issues with the RMQ.

### Related Issue
FIX: #74 

### Proposed Changes

- Microservice for RMQ is enabled in Main.ts
- Changed the durability of queue to true (ref: https://github.com/MassTransit/MassTransit/issues/370#issuecomment-498032635)
- Added optionally chaining in Interceptors

### CODE REVIEW

**Comment by Nazi-pikachu** [comment]
@yuvrajsab can you give feedback on this

**Comment by yuvrajsab** [comment]
> @yuvrajsab can you give feedback on this

hey @Nazi-pikachu, there are too many formatting changes. could you please point out what has changed?

**Comment by Nazi-pikachu** [comment]
Hey @yuvrajsab 
I will create another PR for this , sorry for the formatting mistakes.

**Comment by Nazi-pikachu** [comment]
completed in #83

**Pull request closed without merging**
